version: '3'
services:
  openai:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: openai
    container_name: openai
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
