version: '3'
services:
  openai:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: openai
    container_name: openai
    networks:
      - network1
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
networks:
  network1:
    name: llama-cpp_default
    driver: bridge
    external: true
